# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=3, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='factor',
            field=models.DecimalField(decimal_places=10, help_text='Specifies the difference of the currency to default one.', max_digits=30, verbose_name='factor'),
        ),
    ]
